# Generated by Django 3.2.2 on 2021-05-10 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(default='products/no_image.png', upload_to='products/'),
        ),
    ]
